### ISSUE TITLE
Needs a daemon mode for running unattended

### ISSUE THREAD

**Issue by bmenrigh** [ciscocsirt/netsarlacc#12]
We need to be able to daemonize and interact cleanly with init scripts or similar.  This also means we need a way of gracefully stopping the daemon non-interactively.  Presumably via a single handler but there may be a better "Go" way.

**Comment by Btlyons1** [comment]
If we want to specify how an individual daemonizes the app, then there are a few projects that we could leverage for this that I listed below. 

https://github.com/takama/daemon
https://github.com/sevlyar/go-daemon
https://github.com/fiorix/go-daemon

**Comment by bmenrigh** [comment]
Daemonization mode now working and merged as of commit 6e1bbbee4621bb454640ce82b5fb7d5747148417
