### ISSUE TITLE
Current prints to stdout needs to be cleaned up

### ISSUE THREAD

**Issue by bmenrigh** [ciscocsirt/netsarlacc#14]
Right now there are multiple prints that go to stdout which are fine for testing but won't work for production.  We should cleanup the output.  If we still need output for debugging purposes we should support a debug (or verbose) flag and send the output to stderr instead.

**Comment by Btlyons1** [comment]
Agreed. The plan was to remove them after we completed all the initial features.

**Comment by bmenrigh** [comment]
Now all logging goes to stderr and to syslog or when in daemon mode just to syslog.  Merged as of commit 6e1bbbee4621bb454640ce82b5fb7d5747148417
