### ISSUE TITLE
Start using branches

### ISSUE THREAD

**Issue by Btlyons1** [ciscocsirt/netsarlacc#16]
To avoid any issues, we should start using branches and submitting pull request instead of committing to the master branch.

**Comment by bmenrigh** [comment]
I've started using branches.  I haven't been submitting pull requests though, when I've gotten a feature complete I've just merged the branches.  Is there a compelling reason to use pull over merge (besides the obvious ability to review code pre-merge)?

**Comment by Btlyons1** [comment]
@bmenrigh The idea behind this issue was to allow us to collectively review the code before being merged into master and prevent conflicts in the master branch. This would possibly prevent buggy code from being merged in.

**Comment by bmenrigh** [comment]
I've been using branches.  Once we stamp a version number on it and do a release they'll make even more sense.
