### ISSUE TITLE
No TLS support yet

### ISSUE THREAD

**Issue by bmenrigh** [ciscocsirt/netsarlacc#3]
The code doesn't currently support TLS.  We probably should support listening on multiple different sockets with a flag specifying which sockets are TLS.  That way we can listen on 80, 443, 8000, 8080, an 8443.

**Comment by joeddy** [comment]
looks like we would need to add

import (
    "crypto/tls"
)

cer, err := tls.LoadX509KeyPair("server.crt", "server.key")
config := &tls.Config{Certificates: []tls.Certificate{cer}}
ln, err := tls.Listen("tcp", ":443", config) 


after that its handled the same as http

Need to test this first

**Comment by joeddy** [comment]
I think we will have to run the all the listeners in different go routine, so that they could run at the same time without causing issues.

**Comment by bmenrigh** [comment]
Yeah I agree, we should have a list of interface + port + protocols to listen on and then iterate over each spawing a goroutine to do the listening and accept on each.

**Comment by bmenrigh** [comment]
TLS support has been added as of commit 39767c2b9eb25efee823f72ae33ee7778a058c6d
