### ISSUE TITLE
Consider migrating from text/template to html/template to prevent  XSS

### ISSUE THREAD

**Issue by bmenrigh** [ciscocsirt/netsarlacc#5]
To quote the go documentation https://golang.org/pkg/text/template/  "To generate HTML output, see package html/template, which has the same interface as this package but automatically secures HTML output against certain attacks."

**Comment by bmenrigh** [comment]
$ curl -v --referer '<script>alert("pwned");</script>' http://127.0.0.1:3333/test/path/here.txt?crap

> <td rowspan="1" colspan="1"><script>alert("pwned");</script></td>

**Comment by bmenrigh** [comment]
Fixed in 7e8e511ef0c79b67c4642750d0749f2f06fd4ca1

    $ curl -v --referer '<script>alert("pwned");</script>' http://127.0.0.1:3333/test/path/here.txt?crap

`<td rowspan="1" colspan="1">&lt;script&gt;alert(&#34;pwned&#34;);&lt;/script&gt;</td>`

**Comment by Btlyons1** [comment]
Have you tested this with our template? I was working with html/template and it wasn't rendering the template properly so I never commit the change. Figuring out the issue was something I was going to work on.
