### ISSUE TITLE
Error reading from connection assumes IO timeout

### ISSUE THREAD

**Issue by bmenrigh** [ciscocsirt/netsarlacc#7]
Before reading from a connection we set a read deadline.  Then when we try to read we check for an error and if an error happened we report it with `fmt.Println("Error reading:", err.Error())`

But then later we try to write to the socket to tell the client it was an io timeout: `work.Connection.Write([]byte("Error I/O timeout. \n"))` however there are other reasons this could error.  For example the client could close the connection before we call read.  If we try to write to a socket that is in an error state we could just compound the trouble.  Instead we should just move on without trying to send anything to the client.

**Comment by Btlyons1** [comment]
I'll just remove that.
